### ISSUE TITLE
Addon not working on v0.21.1 [Bug]

### ISSUE THREAD

**Issue by tankshield** [FreeCAD/FreeCAD-addons#301]
Add on is not working and showing this error

  File "C:\Program Files\FreeCAD 0.21\Mod\Draft\draftutils\todo.py", line 138, in doTasks
    f(arg)
  File "C:\Users\USERNAME\AppData\Roaming\FreeCAD\Mod\BIM\.\BimStatusBar.py", line 272, in setStatusIcons
    ifc_status.set_status_widget(statuswidget)
  File "C:\Users\USERNAME\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_status.py", line 54, in set_status_widget
    toggle_lock(checked)
  File "C:\Users\USERNAME\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_status.py", line 78, in toggle_lock
    FreeCADGui.addWorkbenchManipulator(FreeCADGui.IFC_WBManipulator)
AttributeError: module 'FreeCADGui' has no attribute 'addWorkbenchManipulator'

21:30:30  ToDo.doTasks, Unexpected error:
<class 'AttributeError'>
in <function setStatusIcons at 0x0000027E3CA620D0>(True)
