### PR TITLE
Removed UnicodeUTF8 for compatibility with FreeCAD 0.17

### PR DESCRIPTION
**Pull request by elanlb**
The current addons_installer doesn't work in FreeCAD 0.17. It uses `QtGui.QApplication.UnicodeUTF8`, which was [deprecated in Qt5](https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5#QCoreApplication::UnicodeUTF8_is_deprecated). This error is thrown when trying to run the addons installer:

`type object 'PySide2.QtWidgets.QApplication' has no attribute 'UnicodeUTF8'`

To fix this, I removed `QtGui.QApplication.UnicodeUTF8` every time it is used, as it is now used by default.

### CODE REVIEW

**Comment by elanlb** [comment]
It looks like both me and @afester have pull requests for editing the addons installer. I don't know if those can be merged, so I can edit the file again after @afester's PR gets merged if needed.

**Comment by yorikvanhavre** [comment]
merged
